"""saving first message

Revision ID: 12a763e124b9
Revises: bd9d3fbb55fb
Create Date: 2025-12-05 11:07:17.701291

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12a763e124b9'
down_revision: Union[str, None] = 'bd9d3fbb55fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversation_memory', sa.Column('first_message', sa.String(), nullable=True))
    op.add_column('conversation_memory', sa.Column('last_updated', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversation_memory', 'last_updated')
    op.drop_column('conversation_memory', 'first_message')
    # ### end Alembic commands ###
