"""saving first message

Revision ID: 63a4f3635b69
Revises: ddd579fc9a67
Create Date: 2025-12-09 18:16:20.862496

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63a4f3635b69'
down_revision: Union[str, None] = 'ddd579fc9a67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversation_memory', sa.Column('negotiation_state', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversation_memory', 'negotiation_state')
    # ### end Alembic commands ###
