"""added phone number and email

Revision ID: bd9d3fbb55fb
Revises: cae2ee6f1352
Create Date: 2025-12-04 09:15:36.008862

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd9d3fbb55fb'
down_revision: Union[str, None] = 'cae2ee6f1352'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversation_memory', sa.Column('phone_number', sa.String(), nullable=True))
    op.add_column('conversation_memory', sa.Column('email', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversation_memory', 'email')
    op.drop_column('conversation_memory', 'phone_number')
    # ### end Alembic commands ###
