"""Add vehicle filter fields

Revision ID: cae2ee6f1352
Revises: 
Create Date: 2025-11-24 08:47:59.264893

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cae2ee6f1352'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversation_memory', sa.Column('chassis_no', sa.String(), nullable=True))
    op.add_column('conversation_memory', sa.Column('year', sa.Integer(), nullable=True))
    op.add_column('conversation_memory', sa.Column('engine_cc', sa.Integer(), nullable=True))
    op.add_column('conversation_memory', sa.Column('fuel', sa.String(), nullable=True))
    op.add_column('conversation_memory', sa.Column('mileage', sa.Integer(), nullable=True))
    op.add_column('conversation_memory', sa.Column('transmission', sa.String(), nullable=True))
    op.add_column('conversation_memory', sa.Column('doors', sa.Integer(), nullable=True))
    op.add_column('conversation_memory', sa.Column('price', sa.Integer(), nullable=True))
    op.add_column('conversation_memory', sa.Column('selling_price', sa.Integer(), nullable=True))
    op.add_column('conversation_memory', sa.Column('location', sa.String(), nullable=True))
    op.add_column('conversation_memory', sa.Column('geolocation', sa.String(), nullable=True))
    op.add_column('conversation_memory', sa.Column('next_stage', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversation_memory', 'next_stage')
    op.drop_column('conversation_memory', 'geolocation')
    op.drop_column('conversation_memory', 'location')
    op.drop_column('conversation_memory', 'selling_price')
    op.drop_column('conversation_memory', 'price')
    op.drop_column('conversation_memory', 'doors')
    op.drop_column('conversation_memory', 'transmission')
    op.drop_column('conversation_memory', 'mileage')
    op.drop_column('conversation_memory', 'fuel')
    op.drop_column('conversation_memory', 'engine_cc')
    op.drop_column('conversation_memory', 'year')
    op.drop_column('conversation_memory', 'chassis_no')
    # ### end Alembic commands ###
