"""saving features

Revision ID: ddd579fc9a67
Revises: 12a763e124b9
Create Date: 2025-12-09 14:54:11.835415

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ddd579fc9a67'
down_revision: Union[str, None] = '12a763e124b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversation_memory', sa.Column('features', sa.String(), nullable=True))
    op.add_column('conversation_memory', sa.Column('car_suggestions', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversation_memory', 'car_suggestions')
    op.drop_column('conversation_memory', 'features')
    # ### end Alembic commands ###
